In [1]:
#Basic of numpy array

Numpy stands for Numerical array and is used for handling large Multidimensional array and matrices

Unlike pythons built  in lists numpy provide efficient storage and fast processing for numerical and scientific computations.It offers linear algebra and functions and random number generation it is importanty for data science and machine learning 


Types of array

One dimensional array :
array is type of linear array


In [2]:
import numpy as np
lists=[1,2,3,4,5]
sample_array=np.array(lists)

In [3]:
print("List is ",lists)
print("array is :",sample_array)

List is  [1, 2, 3, 4, 5]
array is : [1 2 3 4 5]


In [4]:
print(type(list))
print(type(sample_array))

<class 'type'>
<class 'numpy.ndarray'>


2 Multi dimensional array

a multi dimensional array is more than one dimension dimension such as row and column 

in simple term we can call array within an array

In [9]:
import numpy as np
list_1=[1,2,3,4]
list_2=[5,6,7,8]
list_3=[9,8,7,6]
smaple_array=np.array([list_1,list_2,list_3])
print("numpy multi dimensional array in python\n",sample_array)

numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
import numpy as np

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1, 
                         list_2,
                         list_3])
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Parameters of a Numpy array

Axis :
Axis of array describes the order of indexing into the array 

Shape : Number of elements along with axis and is returned as a tuple

In [15]:
arrays=np.array([[1,2,3],[4,5,6],[6,7,8],[9,8,7]])
print("Shape of the array\n",arrays.shape)

Shape of the array
 (4, 3)


Rank : 
Rank of the array is simply the number of axes or dimensions it has

In [16]:
# data type in array (dtype)

In [19]:
import numpy as np
sample_array_1=np.array([[0,4,2]])
sample_array_2=np.array([0.2,0.4,0.5])
print("Data type of the array 1",sample_array_1.dtype)
print("Data type of array 2",sample_array_2.dtype)

Data type of the array 1 int32
Data type of array 2 float64


different type of creating array

In [21]:
# 1.Numpy.array() : numpy array object in numpy called as ndarray
import numpy as np
arr=np.array([3,4,5,6])
print("array",arr)

array [3 4 5 6]


In [23]:
var="geeksforgeeks"
arr=np.fromiter(var,dtype="U2")
print(arr)

['g' 'e' 'e' 'k' 's' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [24]:
# 3 numpy.arange() : this is an inbuilt numpy function that return evenly spaced values within a given interval

In [25]:
#  syntax : numpy.arange(start,stop,step,dtype)

In [26]:
import numpy as np
np.arange(1,20,2,dtype=np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [27]:
# different ways to create numpy in python

In [28]:
# 1 creating numpy array by list or tuple

In [29]:
lists=[1,2,3,4,5]
arr=np.array(lists)
print(arr)

[1 2 3 4 5]


In [32]:
import numpy as np
zeros_array=np.zeros((2,3))
ones_array=np.ones((1,2))
full_array=np.full((3,4),2)
arange_array=np.arange(0,10,2)
linespace=np.linspace(0,1,10)
print("zeros array \n",zeros_array)
print(ones_array,full_array,arange_array,linespace)

zeros array 
 [[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]] [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]] [0 2 4 6 8] [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


creating python  numpy using random number generation

In [33]:
# np.random.rand(): creates an array of specified shape and fill it with random values sampled from \
# uniform distribution over[0,1]

In [34]:
# np.arandom randn(): creates an array of specified shape and fill it with random values samples from standard normal 
#distribution

In [39]:
import numpy as np
rand=np.random.rand(2,3)
randn=np.random.randn(3,4)
randint=np.random.randint(1,10,size=(3,3))
print("rand\n",rand)
print("randn\n",randn)
print("randint\n",randint)

rand
 [[0.53841994 0.87768515 0.37153695]
 [0.3223253  0.44018781 0.68030921]]
randn
 [[-0.79861673 -2.71032882 -0.37505715  0.39664812]
 [ 1.44732805  1.28517843  0.59108031 -0.31515969]
 [ 0.23573116  1.57131487 -0.17903516  2.15501186]]
randint
 [[1 6 4]
 [9 2 1]
 [1 9 5]]


creates python numpy array using matrix creation routines 

In [40]:
import numpy as np
identity_matrix=np.eye(3)
diagonal_matrix=np.diag([1,2,3])
zeros_like=np.zeros_like(diagonal_matrix)
ones_like=np.ones_like(diagonal_matrix)
print(identity_matrix)
print(diagonal_matrix)
print(zeros_like)
print(ones_like)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


Numpy array indexing

accessing elements in 1D array

we can access  array start from zero and negative indexing stsrt from -1

In [41]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


accessing array in multi dimensional array
2d array are access by specifying both row and column indexes like : matrix[row,column]

In [42]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1,2])

6


In [47]:
import numpy as np
cube=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,20,30],
                [40,50,60],
                [90,80,70]]])
print(cube[1,2,0])

90


In [45]:
import numpy as np

cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])

16


slicing arrays

It allows us to extract a range of elements using format start:stop:step

For both single dimensional and multidimensional array its same
for both

In [48]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [49]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2,1:3])

[[2 3]
 [5 6]]


Boolean indexing : it allows us to filter an array based on a condition and return only those that mett it

In [51]:
print(arr[arr>3])

[4 5 6]


In [54]:
print(arr[(arr>2) & (arr<5)])

[3 4]


fancy indexing : it is also called as advanced indexing it pick an elment from different position

In [55]:
indexes=[0,2,3]
print(arr[indexes])

[1 3 4]


In [56]:
# reshape numpy array

In [1]:
# Numpy array is a general purpose array -processing package .It provides high performance multidimensional array object and tool for 
#working these arrays objects 

reshape an array using N and M 

In [28]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("array\n",arr)

array
 [1 2 3 4 5 6 7 8 9]


In [29]:
n=arr.size
print(n)

9


In [30]:
N=3


In [31]:
M=n/N

In [33]:
reshaped_arr=arr.reshape((N,M))

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr.resize(3,3)

In [36]:
print(arr)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [37]:
arr.resize(3,2)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
#array split
import numpy as np
arr=np.array([1,2,3,4,5,6])
array=np.array_split(arr,3)
print(array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [40]:
# splitting array into piecses equally using numpy.split()

In [43]:
array=np.split(arr,2)
print(array)

[array([1, 2, 3]), array([4, 5, 6])]


In [44]:
#unequal split of an array using numpy.array_split()

In [45]:
import numpy as np
array=np.arange(13)
result=np.array_split(array,4)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [46]:
print(result)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [47]:
# splitting of an array with an axis 

In [50]:
import numpy as np

# Creating a 2D array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

# Splitting the array into 3 equal parts along the second axis (axis=1)
result = np.split(array, 3, axis=1)

print("2D Array:")
print(array)
print("\nResult after numpy.split() along axis=1:")
print(result)

2D Array:
[[3 2 1]
 [8 9 7]
 [4 6 5]]

Result after numpy.split() along axis=1:
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


In [51]:
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])
result=np.vsplit(matrix,2)

In [52]:
print(result)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [56]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
add=np.add(a,b)
sub=np.subtract(a,b)
multiply=np.multiply(a,b)
division=np.divide(a,b)
exponential=np.power(a,b)
modulas=np.mod(a,b)
print(add)
print(sub)
print(multiply)
print(division)
print(modulas)

[  7  77  23 130]
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[ 1  2  3 10]


In [58]:
import numpy as np

input_1=10
input_2=20
out=np.minimum(input_1,input_2)
print(out)

10


In [63]:
inp_1=[10,890,45]
inp_2=[2,0,np.nan]
result=np.minimum(inp_1,inp_2)

In [64]:
print(result)

[ 2.  0. nan]


In [65]:
result=np.maximum(inp_1,inp_2)
print(result)

[ 10. 890.  nan]


In [69]:
arr = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4, ]] 


In [73]:
print(np.mean(arr,axis=1))

[24.  15.  16.8]


In [74]:
#transpose of matrix 
my_array=np.array([[1,2,3],[4,5,6]])
print(np.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


In [76]:
my_array.flatten()

array([1, 2, 3, 4, 5, 6])

Task

You are given a X integer array matrix with space separated elements ( = rows and  = columns).
Your task is to print the transpose and flatten results.

Input Format

The first line contains the space separated values of  and .
The next  lines contains the space separated elements of  columns.

Output Format

First, print the transpose array and then print the flatten.

In [78]:
import numpy

# Read N and M
N, M = map(int, input().strip().split())

# Read N lines of input, each with M numbers
arr = numpy.array([input().strip().split() for _ in range(N)], int)

# Print transpose
print(numpy.transpose(arr))

# Print flatten
print(arr.flatten())


 3 3 
 4 5
 2 3
 3 4


[[4 2 3]
 [5 3 4]]
[4 5 2 3 3 4]
