Task

You are given two integer arrays,  and  of dimensions X.
Your task is to perform the following operations:

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )
Note
There is a method numpy.floor_divide() that works like numpy.divide() except it performs a floor division.

Input Format

The first line contains two space separated integers,  and .
The next  lines contains  space separated integers of array .
The following  lines contains  space separated integers of array .

Output Format

Print the result of each operation in the given order under Task.

In [3]:
import numpy as np
N,M=map(int,input().strip().split())
A=np.array([input().strip().split() for _ in range(N)],int)
B=np.array([input().strip().split() for _ in range(N)],int)


 2 3
 2 3 3
 2 3 4
  5 6 7
 5 6 7


In [5]:
print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.floor_divide(A, B))
print(np.mod(A, B))
print(np.power(A, B))

[[ 7  9 10]
 [ 7  9 11]]
[[-3 -3 -4]
 [-3 -3 -3]]
[[10 18 21]
 [10 18 28]]
[[0 0 0]
 [0 0 0]]
[[2 3 3]
 [2 3 4]]
[[   32   729  2187]
 [   32   729 16384]]


Task
You are given a 1-D array, . Your task is to print the ,  and  of all the elements of .

Note
In order to get the correct output format, add the line  below the numpy import.

Input Format

A single line of input containing the space separated elements of array .

Output Format

On the first line, print the  of A.
On the second line, print the  of A.
On the third line, print the  of A.

In [6]:
import numpy
numpy.set_printoptions(legacy='1.13')

my_array=numpy.array(list(map(float,input().split())))
print(numpy.floor(my_array))
print(numpy.ceil(my_array))
print(numpy.rint(my_array))

 1.1 2.2 3.3 4.4 5.5 6.6 7.7


[ 1.  2.  3.  4.  5.  6.  7.]
[ 2.  3.  4.  5.  6.  7.  8.]
[ 1.  2.  3.  4.  6.  7.  8.]


Task

You are given a 2-D array with dimensions X.
Your task is to perform the  tool over axis  and then find the  of that result.

Input Format

The first line of input contains space separated values of  and .
The next  lines contains  space separated integers.

Output Format

Compute the sum along axis . Then, print the product of that sum.

Sample Input

In [7]:
import numpy
N, M = map(int, input().split())

# Read N lines of input and form a numpy array
arr = numpy.array([list(map(int, input().split())) for _ in range(N)])

result=numpy.sum(arr,axis=0)
print(numpy.prod(result))


 2 2
 2 4 
 5 6


70


Task

You are given a 2-D array of size X.
Your task is to find:

The mean along axis 
The var along axis 
The std along axis 
Input Format

The first line contains the space separated values of  and .
The next  lines contains  space separated integers.

Output Format

First, print the mean.
Second, print the var.
Third, print the std.

Matrix manupulation in python

In python matrix can be implemented as 2D list and 2D array .formatting matrix from latter 

opeartion on matrix:
1.add(): this function is used to perform element wise matrix adition
2.subtract(): this element is used to perform element wise matrix subtraction
3.divide(): this element is used tpo perform element wise matrix division

In [9]:
import numpy 
x=np.array([[1,2],[4,5]])
y=np.array([[6,7],[9,8]])
print(numpy.add(x,y))
print(numpy.subtract(x,y))
print(numpy.divide(x,y))

[[ 7  9]
 [13 13]]
[[-5 -5]
 [-5 -3]]
[[ 0.16666667  0.28571429]
 [ 0.44444444  0.625     ]]


In [10]:
print(numpy.multiply(x,y))

[[ 6 14]
 [36 40]]


In [11]:
print(numpy.dot(x,y))

[[24 23]
 [69 68]]


In [12]:
print(numpy.sqrt(x))

[[ 1.          1.41421356]
 [ 2.          2.23606798]]


In [13]:
print(numpy.sum(y))

30


In [14]:
print(numpy.sum(y,axis=0))

[15 15]


In [15]:
print(x.T)

[[1 4]
 [2 5]]


product of vector and matrix in numpy

1.Inner product of  vector and matrix 

In [16]:
import numpy as np

In [17]:
a=np.array([2,6])
b=np.array([5,6])
print(np.inner(a,b))

46


In [18]:
print(np.outer(a,b))

[[10 12]
 [30 36]]


In [19]:
print(np.cross(a,b))

-18


In [20]:
a=np.array([[1,2,3],[6,7,8]])
b=np.array([[5,6,7],[2,3,4]])
print(np.inner(a,b))

[[ 38  20]
 [128  65]]


In [21]:
print(np.outer(a,b))

[[ 5  6  7  2  3  4]
 [10 12 14  4  6  8]
 [15 18 21  6  9 12]
 [30 36 42 12 18 24]
 [35 42 49 14 21 28]
 [40 48 56 16 24 32]]


In [22]:
print(np.cross(a,b))

[[-4  8 -4]
 [ 4 -8  4]]


Inverse a matris using numpy

numpy.linalg.inv(a): used to find the inverse

In [24]:
import numpy as np
a=np.array([[6,1,2],[5,6,7],[9,3,4]])
print(np.linalg.inv(a))

[[-0.17647059 -0.11764706  0.29411765]
 [-2.52941176 -0.35294118  1.88235294]
 [ 2.29411765  0.52941176 -1.82352941]]


In [25]:
A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])
print(np.linalg.inv(A))

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


The inner product of vector for 1-D array using numpy in python

In [27]:
import numpy as np
array1=np.array([2,3])
array2=np.array([9,5])
result=np.inner(array1,array2)
print(result)

33


In [28]:
result=numpy.outer(array1,array2)
print(result)

[[18 10]
 [27 15]]


In [29]:
#numpy.dot() in numpy

In [30]:
# numpy.vdot()

Eigenvalues and eigenvectors are fundamental concepts ain ;inear algebra used in various applications such as matrix diagnolization ,stbility analysis and data analysis 

random sampling in numpy randomint() function

In [31]:
import numpy as np
out_arr=np.random.randint(low=2,high=6,size=5)
print(out_arr)

[2 3 2 2 3]


In [35]:
#here low=4 is work as high if High is None
out_arr=np.random.randint(low=4,size=(2,3))
print(out_arr)

[[3 1 3]
 [0 2 1]]


In [36]:
out_arr=np.random.randint(2,9,(2,3,4))
print(out_arr)

[[[6 8 7 3]
  [8 5 4 5]
  [2 4 7 6]]

 [[6 8 3 3]
  [4 5 5 3]
  [4 4 8 4]]]


Normal distribution in numpy 

The normal distribution also known as gaussian distribution is one of the most important distribution in statistics and data science

It is widely used to model real-world phenamena such as IQ scores ,heart rates ,test results and many naturally occuring events

In [37]:
# numpy.random.normal() method it has three key parameters

In [38]:
#loc specifies the center of the distribution where the peak of the bell curve exists

In [40]:
# scale : determine sthe spread of the data of the distribution contriolling how flat or narrow the graph is 

In [41]:
# size : defines the shape of the returned array

In [42]:
# generate the single random number

In [44]:
import numpy as np
random_number=np.random.normal()
print(random_number)

1.8317148814152426


In [45]:
# generate an array of random numbers

In [48]:
random_number=np.random.normal(size=5)
print(random_number)

[-0.82257344 -0.13596435  0.40697873 -0.76666068  1.4665345 ]


In [52]:
random_number=np.random.normal(loc=0,scale=20,size=5)
print(random_number)

[  2.09532652 -19.90348592  26.52856209  22.30769762  -5.5145599 ]


In [53]:
import numpy as np
import matplotlib.pyplot as plt