Numpy(Numerical Python) is a fundamental library for python numerical computing
Key features:
N-Dimensional Array
Array with High performance
Element wise Computation 
Verctorization
Linear algebra


In [1]:
import numpy as np

In [3]:
# Using ndarray : The array object is called as ndarray.Numpy array are created 
#using array() function

In [8]:
#creating 1D array
one_D=np.array([2,3,4])
two_D=np.array([[2,3],[4,5]])
three_D=np.array([[[3,4,5],[6,7,8]],[[1,2,3],[0,4,3]]])
print("One D array\n",one_D)
print("Two D array\n",two_D)
print("three D array\n",three_D)

One D array
 [2 3 4]
Two D array
 [[2 3]
 [4 5]]
three D array
 [[[3 4 5]
  [6 7 8]]

 [[1 2 3]
  [0 4 3]]]


In [10]:
# using Numpy function
Zeros=np.zeros((3,3))
Ones=np.ones((2,2))
Arange=np.arange(0,10,2)
print("zeros\n",Zeros)
print("Ones\n",Ones)
print("Arange\n",Arange)

zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones
 [[1. 1.]
 [1. 1.]]
Arange
 [0 2 4 6 8]


In [12]:
# array indexing
import numpy as np
arr1=np.array([1,2,3,4,5,6,7])
print(arr1[4])
print(arr1[-2])


5
6


In [14]:
arr2=np.array([[[1,2,3],[3,4,5]],[[7,8,9],[4,5,6]]])

In [15]:
print(arr2[1,1,1])

5


In [16]:
#Numpy Basic operation

In [17]:
# Element wise operation : we can perform arthematical operation like 
# addition ,substraction,multiplication and division on Numpy array

In [18]:
x=np.array([1,2,3])
y=np.array([4,5,6])
add=x+y
print("addition",add)
sub=x-y
print("substraction",sub)
multiply=x*y
print("multiplication",multiply)
divide=x/y
print("division",divide)

addition [5 7 9]
substraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]


In [20]:
# absolute in numpy
arr=np.array([-3,-1,0,1,3,0.9])
print(abs(arr))

[3.  1.  0.  1.  3.  0.9]


In [21]:
# Binary opeartion
z=np.add(x,y)
print(z)

[5 7 9]


In [23]:
#  Numpy ufuncs
import numpy as np
a=np.array([0,np.pi/2,np.pi])
print("Sine vlaues of array elements ",np.sin(a))

Sine vlaues of array elements  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [25]:
a=np.array([0,1,2,3])
print("exponential of array elements",np.exp(a))

exponential of array elements [ 1.          2.71828183  7.3890561  20.08553692]


In [26]:
print("square root of array elements",np.sqrt(a))

square root of array elements [0.         1.         1.41421356 1.73205081]


In [27]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Array is of type",type(arr))

Array is of type <class 'numpy.ndarray'>


In [28]:
print("NO of dimensions",arr.ndim)

NO of dimensions 2


In [29]:
print("shape of array",arr.shape)

shape of array (2, 3)


In [30]:
print("size of array",arr.size)

size of array 6


In [32]:
print("array stores elements of type:",arr.dtype)

array stores elements of type: int32
